markdown: kramdown
permalink: /:year/:month/:title 
title: Xingxing Huang
url: http://www.mesule.com
subscribe: http://www.mesule.com/feed
exclude: [ README.md, newpost.rb ]
domain: www.mesule.com
author: CnFeat
email: CnFeat@gmail.com
twitterID: feat
disqusShortname: cnfeat
safe: true